### ISSUE TITLE
PSCX installation adds wrong path to $env:PSModulePath

### ISSUE THREAD

**Issue by juneb** [Pscx/Pscx#1]
When you use Install-Module -Scope CurrentUser, the installer adds:
    C:\Program Files (x86)\PowerShell Community Extensions\Pscx3\ 
to $env:PSModulePath even though the module is installed at:
    $home\Documents\WindowsPowerShell\Modules.

The module still auto-loads because $home\Documents\WindowsPowerShell\Modules is a default PSModulePath, but there's now a path in PSModulePath that doesn't exist.

**Comment by rkeithhill** [comment]
When you use `Install-Module` PSCX doesn't touch the PSModulePath at all.  The machine to install is completely controlled by the `PowerShellGet` provider.  However, older versions of PSCX that use an MSI (ones you would download from CodePlex) do modify the PSModulePath.  My guess is that you already PSCX installed via MSI on the system before you installed using Install-Module.

**Comment by juneb** [comment]
Understand. I'll just remove the old path. Thanks!

**Comment by rkeithhill** [comment]
I'm going to close this as all new versions of PSCX will be made available only via the PSGallery.  No more MSI's for me (I hope!).  :-)
