### ISSUE TITLE
load the module manually

### ISSUE THREAD

**Issue by georgejean** [Pscx/Pscx#10]
Powershell Version: 5.0.10586.494.
OS: Windows 10.
PSCX version: 3.2.2.

I'm still a novice and ask you to forgive me if my question sounds stupid.

I would like to use the pscx module, but I think I don't need all its functions and cmdlets (for my first uses) and I would like to take the time to explore it slowly .
So I would find a way to install the module without automatic loading at powershell startup.
Instead of proceeding in the conventional manner
```powershell
Install-Module -Name Pscx 
```
I've tried this
```powershell
Save-Module -Name Pscx -Path My_Path 
```
where `My_Path` is not part of `$env:psmodulepath`.
And then
```powershell
import-module "My_Path\Pscx\3.2.2\Pscx.psm1"
```
but it does not work and I get this error message (Sorry, there are a few french sentences):
```powershell
La propriété « ModulesToImport » est introuvable dans cet objet. Vérifiez qu’elle existe.
Au caractère C:\ScriptsPowershell\Pscx\3.2.2\Pscx.psm1:141 : 11
+ $keys = @($Pscx:Preferences.ModulesToImport.Keys)
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

La propriété « ShowModuleLoadDetails » est introuvable dans cet objet. Vérifiez qu’elle existe.
Au caractère C:\ScriptsPowershell\Pscx\3.2.2\Pscx.psm1:142 : 5
+ if ($Pscx:Preferences.ShowModuleLoadDetails)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

La propriété « ShowModuleLoadDetails » est introuvable dans cet objet. Vérifiez qu’elle existe.
Au caractère C:\ScriptsPowershell\Pscx\3.2.2\Pscx.psm1:227 : 5
+ if ($Pscx:Preferences.ShowModuleLoadDetails)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
```

Is there a way to install the pscx module so that we can choose whether to charge the module ( with full functionality ) at every powershell session?
( I 'd also like to keep the automatic loading of my other modules).

Kind regards.

PS: feel free to edit my message to correct my bad English .

**Comment by rkeithhill** [comment]
Do you still get the error if you execute:
```
import-module "My_Path\Pscx\3.2.2\Pscx.psd1"
```
Note the extension `.psd1`.

**Comment by georgejean** [comment]
Great, loading the powerShell module manifest solves the problem.

Thank you very much!

**Comment by georgejean** [comment]
Great, loading the powerShell module manifest solves the problem.

Thank you very much!

PS: Strangely, the single instruction works very well
```powershell
import-module "My_Path\Pscx\3.2.2\Pscx.psd1"
```
but the two
```powershell
import-module "My_Path\Pscx\3.2.2\Pscx.psm1" # doesn't work
import-module "My_Path\Pscx\3.2.2\Pscx.psd1"
```
don't seem to load the module. I don't know why...

**Comment by rkeithhill** [comment]
In general, if a module has both a PSD1 file and a PSM1 file, always import using the PSD1 file.  That file declares extra stuff the module needs.  If there is *only* a PSM1 file, then you can import the PSM1 file.

**Comment by georgejean** [comment]
ok, thanks.
