### ISSUE TITLE
Expand-Archive: invalid Format argument

### ISSUE THREAD

**Issue by ilpianista** [Pscx/Pscx#12]
The [Expand-Archive man page](https://github.com/Pscx/Pscx/blob/master/Src/PscxHelp/Help/ExpandArchive.xml) references a `Format` parameter. There's even [an example of its usage](https://github.com/Pscx/Pscx/blob/master/Src/PscxHelp/Help/ExpandArchive.xml#L88).

However when you try to invoke `Expand-Archive` with `Format`, the following error occurs:

```
Expand-Archive : A parameter
At line:1 char:16
+ Expand-Archive -Format Zip -Path foo.exe
+                ~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Pscx.Commands.IO.Compression.ExpandArchiveCommand
```

**Comment by ilpianista** [comment]
So it seems that Format has been removed [by this commit](https://pscx.codeplex.com/SourceControl/diff/file/view/107799?fileId=Trunk%2FSrc%2FPscx%2FCommands%2FIO%2FCompression%2FExpandArchiveCommand.cs&olderChangeSetId=62202), but the help page still refers to it.

**Comment by rkeithhill** [comment]
Yeah, the help is not correct.  Thanks for reporting this.
