### ISSUE TITLE
Import-VisualStudioVars - add support for Visual Studio 2017 (RC)

### ISSUE THREAD

**Issue by cristobalito** [Pscx/Pscx#19]
I recently downloaded the release candidate for Visual Studio 2017 (Enterprise) onto a new environment. I took the opportunity to use the Import-VisualStudioVars command to ensure that my general powershell environment was set up as a developer command prompt. 

However, it's pretty obvious that this isn't (yet) supported and that there may be some problems implementing it. Firstly, it appears that VS2017(RC) appears to use a different folder structure by default - Microsoft have dropped the 'Microsoft Visual Studio xx.x' convention under Program Files (x86) and have moved the version under a 'Microsoft Visual Studio' folder i.e. 'Microsoft Visual Studio\2017'. Furthermore, they have added the edition to the folder structure, so my install is actually located under 'Microsoft Visual Studio\2017\Enterprise'. The folder structure under this folder appears to be as before.

**Comment by cristobalito** [comment]
Just realised that version 150 is supported - could possibly add 2017 to the pattern matching in Pscx.Utility.psm1 as a nice to have.

**Comment by cristobalito** [comment]
Submitted a pull request (#20) to add support for 2017 friendly name when using Import-VisualStudioVars.

**Comment by rkeithhill** [comment]
150 is supported but unfortunately it relies on an environment variable convention that VS 2017 no longer seems to follow.  :-(

**Comment by cristobalito** [comment]
@rkeithhill I'd also noticed that earlier and figured it was an issue with the RC. Adding the environment variable worked fine. Any suggestions regarding how to proceed - I'm happy to do the work but would appreciate any input you might have on the matter.

**Comment by onovotny** [comment]
@rkeithhill this might be useful --there's now a PS module to locate VS 2017 instances https://github.com/Microsoft/vssetup.powershell

It could be added as a dependency and used by Pscx to properly locate available VS 2017 instances

**Comment by rkeithhill** [comment]
Thanks for the pointer!
