### ISSUE TITLE
Outdated helptext for `Import-StudioVersion`'s `VisualStudioVersion` parameter

### ISSUE THREAD

**Issue by i-give-up** [Pscx/Pscx#34]
It says "Valid values are 2008, 2010, 2012 and 2013" 

https://github.com/Pscx/Pscx/blob/0444d473d3dd445ad7b5fd4fc7d46f47c5362483/Src/Pscx/Modules/Utility/Pscx.Utility.psm1#L2165-L2167

when in fact the code seems to allow for many more values

https://github.com/Pscx/Pscx/blob/0444d473d3dd445ad7b5fd4fc7d46f47c5362483/Src/Pscx/Modules/Utility/Pscx.Utility.psm1#L2186-L2189

So it seems like the helptext should be updated.

Also I wonder if there's some way for `Get-Help` to read valid values from `ValidateSet` instead of having to write all the valid values in the helptext manually.

**Comment by rkeithhill** [comment]
Thanks for the report.  We have a home grown help build system that is probably not worth investing much time in.  The plan, probably when I redo PSCX for PS Core, is to move to platyPS.  If that supports this feature then great.  If it doesn't then we can make the suggestion against that project.

**Comment by rkeithhill** [comment]
3.3.1 has been published with this fix.
