### ISSUE TITLE
`Select-VSSetupInstance` ignores VS 2017 Build Tools by default

### ISSUE THREAD

**Issue by i-give-up** [Pscx/Pscx#36]
Relevant lines

https://github.com/Pscx/Pscx/blob/0444d473d3dd445ad7b5fd4fc7d46f47c5362483/Src/Pscx/Modules/Utility/Pscx.Utility.psm1#L2260-L2262

I've installed VS 2017 Build Tools. If I try running `Import-VisualStudioVars 2017 amd64`, it gets the wrong path i.e. `C:\VC\Auxiliary\Build\vcvarsall.bat`.

After looking around a bit, it seems like you have to explicitly use the `-Product` parameter to select Build Tools, as shown [here](https://github.com/Microsoft/vssetup.powershell/wiki/Selecting-an-Instance#selecting-other-products).

So, I think what would work for all (Build Tools and regular Visual Studio) is to run `Select-VSSetupInstance` with `-Product *`

``` posh
Select-VSSetupInstance -Product * -Version '[15.0,16.0)' -Require Microsoft.VisualStudio.Component.VC.Tools.x86.x64  
```

**Comment by rkeithhill** [comment]
Good catch!  I have a full install of VS 2017 so I didn't run into this issue.  I'll push out an update tomorrow with your fix.

**Comment by rkeithhill** [comment]
3.3.1 has been published with this fix.
