### ISSUE TITLE
Using 'Install-Module Pscx' results in a 2.1.0.0 installation.

### ISSUE THREAD

**Issue by Paebbels** [Pscx/Pscx#4]
Hello,

I tried to reinstall PSCX 3.2.1 on my machine, so I can write a documentation chapter for one of my projects. When I run `Install-Module Pscx`, version 2.1.0.0 gets installed ...

**Comment by rkeithhill** [comment]
Hmm, that doesn't make sense as I never published that version to the PSGallery.  The first version I published there was 3.1.0.0.  Is it possible you have this version from a previous installation?

**Comment by Paebbels** [comment]
Yes I assume it's falling back to an previous 2.1 installation. I deleted every pscx folder on my system, but it still finds an old 2.1 ....

If I use the proposed method with `Save-Module` + `Install-Module`, it's installing 3.2.1.0 ...

I think this issue can be closed because it's some strange behavior on my machine.
