### ISSUE TITLE
Import-VisualStudioVars fails when workload for VC isn't installed

### ISSUE THREAD

**Issue by goliat43** [Pscx/Pscx#41]
Not sure why, but the code checks for Visual Studio tool path with requirement of "Microsoft.VisualStudio.Component.VC.Tools.x86.x64".

    PS C:\Users\username> Import-VisualStudioVars 2017
    Convert-Path : Cannot find path 'C:\Common7\Tools\VsDevCmd.bat' because it does not exist.
    At C:\Program Files\WindowsPowerShell\Modules\pscx\3.3.0\Modules\Utility\Pscx.Utility.psm1:2205     char:34
    + ...     $batchFilePath = Convert-Path (Join-Path $ComnTools VsDevCmd.bat)
    +                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Common7\Tools\VsDevCmd.bat:String) [Convert-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ConvertPathCommand

This will fail on machines where "Desktop development with C++" workload wasn't selected during Visual Studio install. I don't think there's any reason to require this particular workload as VsDevCmd.bat is installed with other workloads than VC as well. I think any VS workload that includes MSBuild would work (and perhaps others as well?).

I believe it could be changed to (Pscx.Utility.psm1:2253)

                '150|2017' {
                if ((Get-Module -Name VSSetup -ListAvailable) -eq $null) {
                    Write-Warning "You must install the VSSetup module to import Visual Studio variables for this version of Visual Studio."
                    Write-Warning "Install this PowerShell module with the command: Install-Module VSSetup -Scope CurrentUser"
                    throw "VSSetup module not installed, unable to import Visual Studio environment variables."
                }
                Import-Module VSSetup -ErrorAction Stop
                $installPath = Get-VSSetupInstance | 
                               Select-VSSetupInstance -Version '[15.0,16.0)' -Require Microsoft.Component.MSBuild | 
                               Select-Object -First 1 -ExpandProperty InstallationPath
                Push-EnvironmentBlock -Description "Before importing VS 2017 $Architecture environment variables"
                FindAndLoadBatchFile "$installPath/Common7/Tools" $ArchSpecified -IsAppxInstall
            }

**Comment by rkeithhill** [comment]
The `convert-path` issue has been fixed and is waiting to be merged via PR #43 which you commented on.
And RequireWorkload` is now a parameter you can pass to this function.  There is still a bit more work to do this function - part of which is coming up with a reasonable default value for the `RequireWorkload` parameter.

**Comment by rkeithhill** [comment]
3.3.1 has been published with this fix.
