### ISSUE TITLE
Pscx includes commands already available

### ISSUE THREAD

**Issue by musm** [Pscx/Pscx#54]
On powershell 6
```
Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change  its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to
install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
ackageManagement\Install-Package : The following commands are already available on this system:'Expand-Archive,Get-Hash,Get-ShortPath,help,Invoke-NullCoalescing,prompt,Format-Hex,Get-Help,Get-Uptime'. This module 'Pscx' may override the existing commands. If you still want to install this module 'Pscx', use -AllowClobber parameter.
At C:\program files\powershell\6.0.2\Modules\PowerShellGet\1.6.0\PSModule.psm1:2057 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

**Comment by crunk1** [comment]
+1 verified on PS 5.1 and 6.0.2, Win 10 Pro

**Comment by g-uru** [comment]
+1 verified on  Win 10 Pro x64

--------------1-----------------
> $PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  251
--------------1-----------------

--------------2-----------------
> Install-Module -Name Pscx -RequiredVersion 3.2.2
The following commands are already available on this system:
'gcb,Expand-Archive,
Format-Hex,Get-Hash,help,
Invoke-NullCoalescing,prompt,Get-Clipboard,Get-Help,
Set-Clipboard'. This module 'Pscx'
--------------2-----------------

--------------3-----------------
>Get-InstalledModule
Version              Name                                Repository           Description                         
-------              ----                                ----------           -----------                         
1.1.7.0              PackageManagement                   PSGallery            PackageManagement (a.k.a. OneGet)...
0.7.1                posh-git                            PSGallery            Provides prompt with Git status s...
1.6.0                PowerShellGet                       PSGallery            PowerShell module with commands f...
1.2                  PSReadLine                          PSGallery            Great command line editing in the...
--------------3-----------------

--------------4-----------------
> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        chocolateyProfile                   {TabExpansion, Update-SessionEnvironment, refreshenv}
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clea... Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object... Script     1.1.7.0    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get... Script     0.7.1      posh-git                            {Add-PoshGitToProfile, Add-SshKey, Enable-GitColors, ... Script     1.6.0      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-Ro... Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remo...
--------------4-----------------

--------------5-----------------
> Get-InstalledModule

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.1.7.0              PackageManagement                   PSGallery            PackageManagement (a.k.a. OneGet)... 0.7.1                posh-git                            PSGallery            Provides prompt with Git status s... 1.6.0                PowerShellGet                       PSGallery            PowerShell module with commands f... 1.2                  PSReadLine                          PSGallery            Great command line editing in the...
--------------5-----------------

**Comment by Rutix** [comment]
In issue #23 they mentioned that they will leave it for 3.2.x and after that they were going to break up Pscx in smaller modules. I don't know if any work is already set in motion for that plan.

**Comment by musm** [comment]
seems ok now?

**Comment by JohnL4** [comment]
Not ok now.

```
PS C:\Windows\system32# Install-Module Pscx -Scope CurrentUser

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
PackageManagement\Install-Package : The following commands are already available on this
system:'gcb,Expand-Archive,Format-Hex,Get-Hash,help,prompt,Get-Clipboard,Get-Help,Set-Clipboard'. This module 'Pscx'
may override the existing commands. If you still want to install this module 'Pscx', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Pack
   ageManagement.Cmdlets.InstallPackage

PS C:\Windows\system32# get-host | sel version

Version
-------
5.1.17763.1007
```

Windows Server 2019 Std, version 1809, build 17763.1039, handed to me on a VM by my IT folks.

Better not say "Just upgrade!" >:(

**Comment by tjmoore** [comment]
Same in PowerShell 7 with Pscx 3.3.2

```
Install-Module Pscx -Scope CurrentUser   
                                                                                                                        
Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure
 you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
Install-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9709
Line |
9709 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The following commands are already available on this
     | system:'Expand-Archive,Format-Hex,help,prompt,Dismount-VHD,Get-Clipboard,Get-Help,Get-Uptime,Join-String,Mount-VHD,Set-Clipboard'. This module 'Pscx' may override
     | the existing commands. If you still want to install this module 'Pscx', use -AllowClobber parameter.
```
