### ISSUE TITLE
Remove-Module Pscx does not restore the default aliases.

### ISSUE THREAD

**Issue by Paebbels** [Pscx/Pscx#6]
Hello,

when I remove (unload) the Pscx module, it does not restore the default aliases in the system. For example `cd` can not be used anymore.

I don't know if there is any hook for the `Remove-Module` call, which can trigger an unload function in Pscx. If this it not the case, is it possible to provide a `Unregister-Pscx` command, which restores old aliases and whatever, before unloading the Pscx module?

Regards
    Patrick

**Comment by rkeithhill** [comment]
There is a way to catch module unload. I'll look into restoring that alias.

**Comment by Paebbels** [comment]
Hello,

I don't you need to restore all changes. And it might be difficult if Pscx overlaps with similar extensions, but I think important aliases like `cd` should be restored :).

Regards
    Patrick

**Comment by rkeithhill** [comment]
I've been looking at this and it is turning out to be a bugger.  I can fix the alias in the Module Remove scriptblock but PowerShell sees the alias as associated with the module and still removes it. Grr.

**Comment by Paebbels** [comment]
Oh yes, PowerShell can be stubborn from time to time :).

**Comment by oising** [comment]
have some half baked script here from 6 years ago... only restores globals -- might do the trick

http://poshcode.org/1773

**Comment by rkeithhill** [comment]
Thanks Oisin.  I'll look at this tonight.  If this doesn't work, I'm going to push 3.2.2 as-is.  Hopefully it will work.  :-)

**Comment by rkeithhill** [comment]
3.2.2 has been pushed to the PowerShell Gallery.  Give it a try.

**Comment by Paebbels** [comment]
Hello,

it works for me.

Regards
    Patrick
