### ISSUE TITLE
Install instruction gives outdated/old version

### ISSUE THREAD

**Issue by goliat43** [Pscx/Pscx#67]
The install command from the readme 'Install-Module Pscx -Scope CurrentUser' seems to give a version '3.3.2' from 1/17/2018 (https://www.powershellgallery.com/packages/Pscx/3.3.2).

For one, this version is missing 'Import-VisualStudioVars 2019'. Is the readme incorrect or could the current release be updated?

**Comment by cristobalito** [comment]
> Is the readme incorrect or could the current release be updated?
The readme is correct but there hasn't been a release since the VS2019 changes were made. I came here to submit a request for a new release and noticed this issue.

**Comment by goliat43** [comment]
Current version on gallery is still old. Any hope of getting it updated or should we find alternate ways to install?

**Comment by xylographe** [comment]
The only file that has changed since v3.3.2 is [`Src/Pscx/Modules/Utility/Pscx.Utility.psm1`](https://github.com/Pscx/Pscx/blob/master/Src/Pscx/Modules/Utility/Pscx.Utility.psm1).

**Comment by goliat43** [comment]
Yes, and that's the problem. Changes to easily get VS2019 vars done in that file. Of course I could hack around it but the point of a gallery IMO is that I shouldn't need to figure out all the details of where and how the modules are installed.

Seems I'm better of just cloning the repo and adding that to module path. But it's a bit unfortunate as this is not what the readme tells us to do. and module handling through PSgallery would be much smoother.
