### ISSUE TITLE
Don't override default Powershell command Expand-Archive

### ISSUE THREAD

**Issue by Antonytm** [Pscx/Pscx#68]
I run my PS script and get this error:
Expand-Archive : A parameter cannot be found that matches parameter name 'DestinationPath'
It is caused by PSCX, because it overrides default command, but doesn't have parameter name 'DestinationPath'. 

I think that agreement should be next: if you override default command, you should use and support same parameters. Otherwise this module causes problems.

**Comment by rkeithhill** [comment]
Well, `Expand-Archive` was developed **years before** there was a built-in command with the same name.  So, there was no way to avoid a parameter name that didn't exist at the time.  :-)  Your best bet, for now, is to import the module with a prefix like `Pscx` then the command becomes `Expand-PscxArchive` and there's no more collision.

There are actually quite a few duplicate command names now that PS has had years to add the missing functionality that PSCX was providing - which is good.  I'm glad to see commands like `Expand-Archive` be made available directly in PS.  But it presents problems on how we should proceed with Pscx.  It's tempting to create a breaking change version like a v4 that rips out all of the duplicate commands.

**Comment by Antonytm** [comment]
The second thing that I faced:
It was actually hard to get rid from PSCX.  

1. Uninstall-Module command didn't work for it
2. Remove-Module didn't work for current PS session
3. When I get all paths, where PS modules are installed $env:PSModulePath.split(';'), PSCX wasn't listed there
4. Uninstall from Add/Remove Programs menu didn't work for PSCX

Finally I found that it was installed in C:\Program Files (x86)\PowerShell Community Extensions\Pscx3 (don't remember, when I installed it, following modification timestamp it was in 2017)

**Comment by rkeithhill** [comment]
Before the PowerShell Gallery existed along with install/uninstall-module, PSCX was provided as an MSI.  The latest version can be installed using `install-module` though.  We no longer distribute an MSI.

**Comment by Liturgist** [comment]
This seems like a barrier to adoption of Pscx for users of modern-day versions of PowerShell. Every supported Windows platform can run PowerShell 5.1 and PowerShell Core versions. (is that correct?)

I need the functionality of ConvertTo-UnixLineEndings, but I am not ready to -AllowClobber replace archive compression and expansion.

Is it possible that Pscx could split the currently redundant duplicate functions off to a separate module that users of PowerShell 4.0 would also install? Are there other ways to handle this?

**Comment by oising** [comment]
@rkeithhill Maybe we should just do it -- last time we looked at this, .net core was all shiny and new -- and very confusing. Pscx v4 should be stripped right down to the valuable stuff, and we just call it a breaking change, and v7.x+ only. Maybe we can encourage more contributors that way...

**Comment by rkeithhill** [comment]
The plan is to rename the `Archive` commands to something like `ArchiveCx` or `ArchiveEx` so they will not clobber the new, built-in commands.
