### ISSUE TITLE
How to use Set-LocationEx?

### ISSUE THREAD

**Issue by E3V3A** [Pscx/Pscx#71]
Hi can you give some examples of how to use: `Set-LocationEx`?
Investigating `cd --` in bash.

**Comment by rkeithhill** [comment]
In v4 beta1 this command has been renamed to `Set-PscxLocation` to make it more consistent with the other Pscx command that provide functionality beyond the built-on command. 

You can do stuff like this with Set-PscxLocation. Note I'm going to redefine the cd alias below to this command to make the samples easier:

```powershell
Set-Alias cd Set-PscxLocation -Option AllScope
cd ~\Documents
cd ...
cd -
cd
cd -2
cd -0
cd +
```
