### ISSUE TITLE
Published code is stale

### ISSUE THREAD

**Issue by jaraco** [Pscx/Pscx#86]
I was hoping to use Pscx to build the libxml libraries for Windows using Visual Studio 2019, but installing from the gallery doesn't include updates from years ago (#61).

Is this project abandoned? Can you provide instructions on how to install the code from source?

**Comment by rkeithhill** [comment]
There is a prerelease of 4.0.0 on PSGallery. You have to use the `-AllowPrerelease` flag to install it.

**Comment by jaraco** [comment]
Oooh! I'll try that. Thanks.

**Comment by jaraco** [comment]
Hmm. I don't have `-AllowPrerelease`. I'm using NuGet 2.8.5.208. `Install-Package` has `-AllVersions` but that doesn't work either. I'll keep trying.

**Comment by rkeithhill** [comment]
You want to use: `Install-Module pscx -AllowPrerelease -AllowClobber -Force`

**Comment by jaraco** [comment]
I found I needed to [first upgrade PowershellGet](https://evotec.xyz/install-module-a-parameter-cannot-be-found-that-matches-parameter-name-allowprerelease/). jaraco/libxml2-win-libraries@7b66aa1.  After that, I'm able to at least request vars for Visual Studio 2019. So thanks!
